name: Specs
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
          ruby-version: '3.0'
      - run: bundle install
      - run: bundle exec rspec
